sudo: required

services:
  - docker

before_install:
  - docker build -t ksikorski1/docker-myfrontend/frontend -f Dockerfile.dev .

scripts:
  -docker run -e CI=true ksikorski1/docker-myfrontend/frontend yarn test