sudo: required

services:
  - docker

before_install:
  - docker build -t ksikorski1/docker-myfrontend -f ./frontend/Dockerfile.dev ./frontend/

scripts:
  -docker run -e CI=true ksikorski1/docker-myfrontend yarn test